server:
  port: 8081

spring:
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: postgres
    password: pg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
#    fetch-registry: true
#    register-with-eureka: true
