server:
  port: 9090
  ssl:
    enabled: true
    key-store: "/Library/Java/JavaVirtualMachines/jdk-18.0.2.1.jdk/Contents/Home/lib/security/cacerts"
    key-store-password: "password"
    key-store-type: "jks"
    key-alias: "okta"

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      routes:
        - id : ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1

okta:
  oauth2:
    issuer: https://dev-18359154.okta.com/oauth2/default
    audience: api://default
    client-id: 0oadm5qnkbDYQo4fi5d7
    client-secret: w9oKAvIqJvnLzo02ew1HJ43J1Pne3EpBXFzlkk-NAF_79n2obBG-rfUZBoufoe0W
    scopes: openid, profile, email, offline_access